// strength recovery pass
// the purpose of this pass is to recover the strength reduction optimizations made by llvm
// to make the code more human readable
// uses metadata to mark original instructions
// ensuring the pass only targets those generated by LLVM's strength reduction

#include <vexa/vexa.h>

// RULE DEFINITIONS HERE
vexa::passes::strength_recovery::shl_mul_rule_t vexa::passes::strength_recovery::shl_mul;
vexa::passes::strength_recovery::lshr_udiv_rule_t vexa::passes::strength_recovery::lshr_udiv;
vexa::passes::strength_recovery::and_urem_rule_t vexa::passes::strength_recovery::and_urem;
std::vector<vexa::passes::strength_recovery::rule_t*> vexa::passes::strength_recovery::rules;

// shl %x, %constant -> mul %x, %(1 << %constant)
bool vexa::passes::strength_recovery::shl_mul_rule_t::does_match(llvm::Instruction* instruction)
{
    if (auto *shl = llvm::dyn_cast<llvm::ShlOperator>(instruction))
        return llvm::isa<llvm::ConstantInt>(shl->getOperand(1));
    return false;
}
llvm::Instruction* vexa::passes::strength_recovery::shl_mul_rule_t::transform(llvm::Instruction* instruction, std::shared_ptr<ir::builder> builder)
{
    uint64_t mul_val = 1ULL << llvm::dyn_cast<llvm::ConstantInt>(instruction->getOperand(1))->getZExtValue(); //pow(2, llvm::dyn_cast<llvm::ConstantInt>(instruction->getOperand(1))->getZExtValue());
    llvm::Value* mul = builder->CreateMul(
                           instruction->getOperand(0),
                           llvm::ConstantInt::get(instruction->getType(), mul_val));
    return llvm::dyn_cast<llvm::Instruction>(mul);
}

// lshr %x, %constant -> udiv %x, %(1 << %constant)
bool vexa::passes::strength_recovery::lshr_udiv_rule_t::does_match(llvm::Instruction* instruction)
{
    if (auto *lshr = llvm::dyn_cast<llvm::LShrOperator>(instruction))
        return llvm::isa<llvm::ConstantInt>(lshr->getOperand(1));
    return false;
}
llvm::Instruction* vexa::passes::strength_recovery::lshr_udiv_rule_t::transform(llvm::Instruction* instruction, std::shared_ptr<ir::builder> builder)
{
    uint64_t udiv_val = 1ULL << llvm::dyn_cast<llvm::ConstantInt>(instruction->getOperand(1))->getZExtValue();
    llvm::Value* udiv = builder->CreateUDiv(
                            instruction->getOperand(0),
                            llvm::ConstantInt::get(instruction->getType(), udiv_val));
    return llvm::dyn_cast<llvm::Instruction>(udiv);
}

// and %a, %constant -> urem %a, %(constant + 1)
    //    - %constant must be one less of a multiple of two (like 15, 31, 63)
bool vexa::passes::strength_recovery::and_urem_rule_t::does_match(llvm::Instruction* instruction)
{
    if (instruction->getOpcode() == llvm::Instruction::And)
    {
        if (auto *C = llvm::dyn_cast<llvm::ConstantInt>(instruction->getOperand(1)))
        {
            const llvm::APInt& val = C->getValue();
            return (val + 1).isPowerOf2();
            // manual calculation below:
            //uint64_t constant = C->getZExtValue() + 1;
            //return (constant != 0) && ((constant & (constant - 1)) == 0);
        }
    }

    return false;
}
llvm::Instruction* vexa::passes::strength_recovery::and_urem_rule_t::transform(llvm::Instruction* instruction, std::shared_ptr<ir::builder> builder)
{
    uint64_t urem_val = llvm::dyn_cast<llvm::ConstantInt>(instruction->getOperand(1))->getZExtValue() + 1;
    llvm::Value* urem = builder->CreateURem(
                            instruction->getOperand(0),
                            llvm::ConstantInt::get(instruction->getType(), urem_val));
    return llvm::dyn_cast<llvm::Instruction>(urem);
}

bool vexa::passes::strength_recovery::analysis::run()
{
    llvm::MDString* md_string = llvm::MDString::get(*context->llvm_context, "vexa.original");
    llvm::MDNode* md_node = llvm::MDNode::get(*context->llvm_context, md_string);

    // mark all instructions before transforming them so we dont break non-optimized original instructions
    for (auto &BB : *builder->get_function())
        for (auto &I : BB)
            for (auto &rule : rules)
                if (rule->does_match(&I))
                    I.setMetadata("vexa.strength_recovery", md_node);

    return false;
}

// look for instructions that matches with our rules.
// and if its not marked as original, apply the rule transformation.
bool vexa::passes::strength_recovery::run()
{
    for (auto &BB : *builder->get_function())
    {
        for (auto it = BB.begin(); it != BB.end();)
        {
            llvm::Instruction *inst = &*it++;
            for (auto &rule : rules)
            {
                if (rule->does_match(inst))
                {
                    if (auto *N = inst->getMetadata("vexa.strength_recovery"))
                    {
                        if (auto *S = llvm::dyn_cast<llvm::MDString>(N->getOperand(0)))
                            if (S->getString() != "vexa.original")
                                goto transform;
                    }
                    else {
transform:
                        builder->SetInsertPoint(inst);
                        llvm::Instruction* transformed = rule->transform(inst, builder);
                        inst->replaceAllUsesWith(transformed);
                        inst->eraseFromParent();

                        llvm::MDString* md_string = llvm::MDString::get(*context->llvm_context, "vexa.transformed");
                        llvm::MDNode* md_node = llvm::MDNode::get(*context->llvm_context, md_string);
                        transformed->setMetadata("vexa.strength_recovery", md_node);
                        break;
                    }
                }
            }
        }
    }

    return false;
}

// get constant from inlineasm calls so we block llvm backend's strength reduction
llvm::Value* vexa::passes::strength_recovery::pre_compilation::get_opaque_constant(uint64_t val, llvm::Type* type) {
    auto* context = &builder->getContext();
    auto* fnType = llvm::FunctionType::get(type, {type}, false);
    auto* inlineAsm = llvm::InlineAsm::get(fnType, "", "=r,0", true);
    llvm::Value* constVal = llvm::ConstantInt::get(type, val);
    return builder->CreateCall(inlineAsm, {constVal});
}

// transform every marked instruction's constants to inlineasm
bool vexa::passes::strength_recovery::pre_compilation::run()
{
    for (auto &BB : *builder->get_function())
    {
        for (auto it = BB.begin(); it != BB.end();)
        {
            llvm::Instruction *inst = &*it++;
            if (auto *N = inst->getMetadata("vexa.strength_recovery"))
            {
                if (auto *S = llvm::dyn_cast<llvm::MDString>(N->getOperand(0)))
                    if (S->getString() == "vexa.transformed")
                    {
                        builder->SetInsertPoint(inst);
                        for (auto it_ = inst->operands().begin(); it_ != inst->operands().end();)
                        {
                            llvm::Use *operand = &*it_++;
                            if (auto C = llvm::dyn_cast<llvm::ConstantInt>(operand->get()))
                            {
                                llvm::Value* opaque = get_opaque_constant(C->getZExtValue(), C->getType());
                                operand->set(opaque);
                            }
                        }
                    }
            }
        }
    }

    return false;
}