#pragma once
#include "../ir/builder.hpp"

namespace vexa {
namespace passes {

// Strength recovery pass.
// The purpose of this pass is to recover the strength reduction optimizations made by llvm.
// To make the code more human readable.
// Uses metadata to mark original instructions.
// Ensuring the pass only targets those generated by LLVM's strength reduction.
class strength_recovery : public vexa::ir::pass
{
public:
    // supported rules
    // shl %x, %constant -> mul %x, %(1 << %constant)
    // lshr %x, %constant -> udiv %x, %(1 << %constant)
    // and %a, %constant -> urem %a, %(constant + 1)
    //    - %constant must be one less of a multiple of two (like 15, 31, 63)

    // if you want to add a new rule, create a new class based on rule_t.
    // and add to the rules vector below. also define it on strength_recovery.cpp.
    class rule_t
    {
    public:
        virtual bool does_match(llvm::Instruction* instruction) = 0;
        virtual llvm::Instruction* transform(llvm::Instruction* instruction, std::shared_ptr<ir::builder> builder) = 0;
    };

    // RULE DECLERATIONS HERE
    class shl_mul_rule_t : public rule_t
    {
    public:
        bool does_match(llvm::Instruction* instruction) override;
        llvm::Instruction* transform(llvm::Instruction* instruction, std::shared_ptr<ir::builder> builder) override;
    } static shl_mul;

    class lshr_udiv_rule_t : public rule_t
    {
    public:
        bool does_match(llvm::Instruction* instruction) override;
        llvm::Instruction* transform(llvm::Instruction* instruction, std::shared_ptr<ir::builder> builder) override;
    } static lshr_udiv;

    class and_urem_rule_t : public rule_t
    {
    public:
        bool does_match(llvm::Instruction* instruction) override;
        llvm::Instruction* transform(llvm::Instruction* instruction, std::shared_ptr<ir::builder> builder) override;
    } static and_urem;
    

    class analysis : public vexa::ir::pass
    {
    public:
        analysis(vexa::context* ctx) : pass(ctx) {}
        bool run() override;
        bool is_recursive() override {
            return false;
        }
    };

    class pre_compilation : public vexa::ir::pass
    {
    public:
        pre_compilation(vexa::context* ctx) : pass(ctx) {}
        bool run() override;
        bool is_recursive() override {
            return false;
        }
        llvm::Value* get_opaque_constant(uint64_t val, llvm::Type* type);
    };

    // ADD RULES HERE
    strength_recovery(vexa::context* ctx) : pass(ctx) {
        rules = {&shl_mul, &lshr_udiv, &and_urem};
    }
    bool run() override;
    bool is_recursive() override {
        return false;
    }

private:
    static std::vector<rule_t*> rules;
};

}
}